{{- if ne .Values.linkis.datasource.initSchema "None" }}
apiVersion: batch/v1
kind: Job
metadata:
  name: init-db
spec:
  template:
    spec:
      volumes:
        - name: init-sql
          configMap:
            name: {{ include "linkis.fullname" . }}-init-sql
            items:
              - key: linkis_ddl.sql
                path: linkis_ddl.sql
              - key: linkis_dml.sql
                path: linkis_dml.sql
      containers:
        - name: init-db
          image: mysql:{{ .Values.linkis.deps.mysql.version }}
          volumeMounts:
            - name: init-sql
              readOnly: true
              mountPath: /db
          command:
            - /bin/bash
            - -ecx
            - >-
              mysql -h{{ .Values.linkis.datasource.host }} -P{{ .Values.linkis.datasource.port }} -u{{ .Values.linkis.datasource.username }} -p{{ .Values.linkis.datasource.password }} --default-character-set=utf8 -e "CREATE DATABASE IF NOT EXISTS {{ .Values.linkis.datasource.database }} DEFAULT CHARSET utf8 COLLATE utf8_general_ci";
              mysql -h{{ .Values.linkis.datasource.host }} -P{{ .Values.linkis.datasource.port }} -u{{ .Values.linkis.datasource.username }} -p{{ .Values.linkis.datasource.password }} -D{{ .Values.linkis.datasource.database }}  --default-character-set=utf8 -e "source /db/linkis_ddl.sql";
              mysql -h{{ .Values.linkis.datasource.host }} -P{{ .Values.linkis.datasource.port }} -u{{ .Values.linkis.datasource.username }} -p{{ .Values.linkis.datasource.password }} -D{{ .Values.linkis.datasource.database }}  --default-character-set=utf8 -e "source /db/linkis_dml.sql"

      restartPolicy: Never
  backoffLimit: 0

{{- end }}
